Add caixasigcb layout
citartech/node-boleto pull request #1
Opened 2019-10-04 14:54 UTC by brenodouglas

Este PR visa adicionar o boleto de cobrança da CAIXA. 

Tarefa: https://trello.com/c/rEJlQYv5

2019-10-04 19:06 UTC, meneguite requested changes
Mano o código esta bem estruturado, mas algumas coisas que imagino estar seguindo o contexto da lib, seria uma boa remover, como o uso extensivo de "var", no js moderno que usamos em nossos projetos nos limitamos sempre que possível a let e const. Comentei tb algumas coisas pontuais no código tb para ajuste. Fiquei também com dúvida quanto as dependências de dev.. por favor da uma conferida se todas listadas ali são realmente de dev.

2019-10-04 19:06 UTC, meneguite commented on banks/caixasigcb/index.js
> +        // TODO
Mano coloca uma explicação melhor do PQ do TODO.. assim quem pegar percebe pq da pendência..

2019-10-04 19:06 UTC, meneguite commented on banks/caixasigcb/index.js
> +// const ediHelper = require('../../lib/edi-helper')
Remove esse comentário aqui tb por favor!

2019-10-07 11:55 UTC, brenodouglas commented
> Mano o código esta bem estruturado, mas algumas coisas que imagino estar seguindo o contexto da lib, seria uma boa remover, como o uso extensivo de "var", no js moderno que usamos em nossos projetos nos limitamos sempre que possível a let e const. Comentei tb algumas coisas pontuais no código tb para ajuste. Fiquei também com dúvida quanto as dependências de dev.. por favor da uma conferida se todas listadas ali são realmente de dev.

@meneguite quais dependencias de dev te deixaram duvidas? Todas estão sendo utilizadas normalmente no projeto.

2019-10-07 13:05 UTC, meneguite commented
> > Mano o código esta bem estruturado, mas algumas coisas que imagino estar seguindo o contexto da lib, seria uma boa remover, como o uso extensivo de "var", no js moderno que usamos em nossos projetos nos limitamos sempre que possível a let e const. Comentei tb algumas coisas pontuais no código tb para ajuste. Fiquei também com dúvida quanto as dependências de dev.. por favor da uma conferida se todas listadas ali são realmente de dev.
> 
> @meneguite quais dependencias de dev te deixaram duvidas? Todas estão sendo utilizadas normalmente no projeto.

Mano nem é uma dúvida se estamos usando ou não.. só queria que confirmasse que as libs como moment e ramda, estão sendo usadas exclusivamente nos testes.

2019-10-07 17:54 UTC, merged